apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: av1sh/user-management:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://localhost:27017/user-management"
        - name: JWT_SECRET
          value: "your-jwt-secret"
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000